apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "real-time.fullname" . }}-config
  labels:
    {{- include "real-time.labels" . | nindent 4 }}
data:
  PHX_HOST: {{ .Values.config.phxHost | quote }}
  KEYCLOAK_URL: {{ .Values.keycloak.url | quote }}
  KEYCLOAK_REALM: {{ .Values.keycloak.realm | quote }}
  SFU_GRPC_ADDR: {{ .Values.sfu.grpcAddr | quote }}
