{{- if not .Values.secretKeyBase.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "real-time.fullname" . }}-secret
  labels:
    {{- include "real-time.labels" . | nindent 4 }}
type: Opaque
data:
  secret_key_base: {{ required "secretKeyBase.value is required when secretKeyBase.existingSecret is not set" .Values.secretKeyBase.value | b64enc | quote }}
{{- end }}
---
{{- if not .Values.redis.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "real-time.fullname" . }}-redis
  labels:
    {{- include "real-time.labels" . | nindent 4 }}
type: Opaque
data:
  url: {{ .Values.redis.url | b64enc | quote }}
{{- end }}
---
{{- if not .Values.rabbitmq.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "real-time.fullname" . }}-rabbitmq
  labels:
    {{- include "real-time.labels" . | nindent 4 }}
type: Opaque
data:
  url: {{ .Values.rabbitmq.url | b64enc | quote }}
{{- end }}
